const $=s=>document.querySelector(s);
let mode='chat',history=[],episode=null,frame=0,playing=false,first=true;
const notes={chat:'Local pretrained language model. Answers can be wrong; arithmetic is checked by a separate exact solver.',math:'Exact rational arithmetic and linear equations. Use explicit multiplication: 3*x + 7 = 22. This result comes from a tool, not unaided neural reasoning.',image:'Learned scene attributes → software renderer. Describe cube, sphere, pyramid or cylinder; color; one to three objects; and small, medium or large.',video:'A learned scene becomes a 2.4-second animation. Motions: still, orbit, bounce, spin. Geometric animation, not photorealistic video.',mesh:'Create basic OBJ + MTL and glTF assets from the same learned scene representation. Up to three geometric objects.',world:'The trained policy chooses six actions in a deterministic synthetic world. Reaches the 256-step horizon or dies. No teacher fallback.'};
const examples={chat:'Ask Poseidon something…',math:'(17 + 5) * 3, or 3*x + 7 = 22',image:'Create two small cyan spheres with orbit motion.',video:'Make three medium purple cubes with bounce motion.',mesh:'Build one large yellow pyramid with still motion.',world:'Run the learned agent in TidePool'};
function setMode(value){mode=value;document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('selected',b.dataset.mode===mode);b.setAttribute('aria-selected',String(b.dataset.mode===mode));});$('#modeNote').textContent=notes[mode];$('#prompt').placeholder=examples[mode];if($('#plannerControls'))$('#plannerControls').hidden=(mode!=='world');}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{if(b.dataset.target)setMode(b.dataset.target);$('#prompt').value=b.dataset.prompt;$('#prompt').focus();});
function message(role,text,backend){if(first){$('#messages').replaceChildren();first=false;}let card=document.createElement('div');card.className='message '+role;let label=document.createElement('div');label.className='message-label';label.textContent=role==='user'?'YOU':role==='error'?'REQUEST ERROR':'POSEIDON';let body=document.createElement('div');body.className='message-body';body.textContent=text;card.append(label,body);if(backend){let meta=document.createElement('div');meta.className='message-backend';meta.textContent=backend;card.append(meta);}$('#messages').append(card);$('#messages').scrollTop=$('#messages').scrollHeight;}
async function request(url,payload){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);return data;}
function excluded(){return [...document.querySelectorAll('.ablations input:checked')].map(x=>x.value);}
$('#promptForm').onsubmit=async e=>{e.preventDefault();let text=$('#prompt').value.trim()||(mode==='world'?'Run survival episode':'');if(!text)return;const activeMode=mode;message('user',text);$('#send').disabled=true;$('#activity').textContent=activeMode==='chat'?'Loading / thinking locally…':'Running '+activeMode+'…';try{let data=await request('/api/respond',{prompt:text,mode:activeMode,history,seed:Number($('#seed').value),disabled_carriers:excluded(),planner:$('#planner')?$('#planner').value:'risk_aware'});message('assistant',data.text,data.backend);if(activeMode==='chat'){history.push({role:'user',content:text},{role:'assistant',content:data.text});history=history.slice(-6);}if(data.links)showArtifact(data);if(data.episode)showWorld(data.episode);if(data.prediction?.routing)showRouting(data.prediction.routing);$('#activity').textContent='Completed locally';$('#prompt').value='';}catch(error){message('error',error.message);$('#activity').textContent='Request failed — see message';}finally{$('#send').disabled=false;refreshStatus();}};
$('#prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#promptForm').requestSubmit();}});
function showRouting(weights){document.querySelectorAll('#routing>div').forEach((row,i)=>{const value=Math.max(0,Math.min(1,Number(weights[i])||0));row.querySelector('b').style.width=value*100+'%';row.querySelector('small').textContent=Math.round(value*100)+'%';});}
function showArtifact(data){playing=false;$('#timeline').hidden=true;$('#visual').replaceChildren();let el;if(data.kind==='video'&&data.links.mp4){el=document.createElement('video');el.controls=true;el.loop=true;el.src=data.links.mp4;}else{el=document.createElement('img');el.src=data.links.gif||data.links.preview;el.alt='Generated '+data.scene.color+' '+data.scene.shape+' scene';}$('#visual').append(el);$('#artifactType').textContent=data.kind.toUpperCase();$('#artifactInfo').textContent=data.text+' '+(data.triangle_count?data.triangle_count+' triangles.':'');$('#downloads').replaceChildren();for(const [name,url]of Object.entries(data.links)){if(name==='preview'||name==='mtl')continue;let a=document.createElement('a');a.href=url;a.download='';a.textContent=name.toUpperCase()+' ↓';$('#downloads').append(a);}}
function drawIdle(){const c=$('#worldCanvas');if(!c)return;const ctx=c.getContext('2d');ctx.fillStyle='#0a1720';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#23413f';for(let i=0;i<7;i++){ctx.beginPath();ctx.ellipse(300,175,55+i*21,25+i*11,-.24,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='#8be4ca';ctx.beginPath();ctx.arc(356,150,5,0,Math.PI*2);ctx.fill();}
function showWorld(data){episode=data;frame=0;playing=true;$('#visual').replaceChildren();const c=document.createElement('canvas');c.id='worldCanvas';c.width=600;c.height=400;c.setAttribute('aria-label','Synthetic survival world');$('#visual').append(c);$('#timeline').hidden=false;$('#scrub').max=Math.max(0,data.trajectory.length-1);$('#artifactType').textContent='BEYOND WORLD';$('#artifactInfo').textContent=(data.survived?'Horizon reached alive':'Died: '+data.death_reason)+' · '+data.steps+' steps · seed '+data.seed+' · '+(data.backend||'Uncertainty Ensemble');$('#downloads').replaceChildren();animateWorld();}
function drawWorld(){if(!episode)return;const ctx=$('#worldCanvas').getContext('2d'),row=episode.trajectory[frame],state=row?.state||{},snap=episode.initial_snapshot;ctx.fillStyle='#091721';ctx.fillRect(0,0,600,400);const size=44,ox=38,oy=55;for(let y=0;y<6;y++)for(let x=0;x<6;x++){const patch=snap.patches[y*6+x],alpha=.14+.35*patch.food;ctx.fillStyle=`rgba(103,197,156,${alpha})`;ctx.fillRect(ox+x*size,oy+y*size,size-4,size-4);ctx.fillStyle='#5b9cae';ctx.fillRect(ox+x*size+4,oy+y*size+size-10,(size-12)*patch.water,3);}const x=state.x??state.position?.[0]??0,y=state.y??state.position?.[1]??0;ctx.fillStyle='#f2b68e';ctx.beginPath();ctx.arc(ox+x*size+20,oy+y*size+20,10,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffe0b9';ctx.lineWidth=2;ctx.stroke();ctx.font='12px Segoe UI';ctx.fillStyle='#a3b8c5';ctx.fillText('TIDEPOOL / SEEDED PATCHES',38,31);ctx.fillText('Initial resource map • agent position replays',38,345);const names=['Health','Energy','Hydration','Stamina'];names.forEach((name,i)=>{let value=row?.next_observation?.[i]??1;ctx.fillStyle='#b9cdd2';ctx.fillText(name,350,85+i*55);ctx.fillStyle='#233741';ctx.fillRect(350,96+i*55,200,6);ctx.fillStyle=value<.25?'#eea276':'#8be4ca';ctx.fillRect(350,96+i*55,200*Math.max(0,Math.min(1,value)),6);});ctx.fillStyle='#eea276';ctx.fillText((row?.action_name||'').toUpperCase()+' / STEP '+(frame+1),350,329);$('#scrub').value=frame;$('#tick').textContent=frame+1;}
let lastFrame=0;function animateWorld(time=0){drawWorld();if(playing&&episode){if(time-lastFrame>70){frame=Math.min(frame+1,episode.trajectory.length-1);lastFrame=time;if(frame===episode.trajectory.length-1)playing=false;}requestAnimationFrame(animateWorld);}}
$('#scrub').oninput=()=>{playing=false;frame=Number($('#scrub').value);drawWorld();};$('#replay').onclick=()=>{if(!episode)return;frame=0;playing=true;animateWorld();};
$('#remember').onclick=async()=>{try{const r=await request('/api/remember',{text:$('#memoryText').value,carrier:$('#carrier').value});$('#memoryStatus').textContent=r.saved?'Fact saved locally.':'Not saved';$('#memoryText').value='';}catch(e){$('#memoryStatus').textContent=e.message;}};
$('#recall').onclick=async()=>{try{const r=await request('/api/respond',{prompt:$('#prompt').value||'memory',mode:'memory',disabled_carriers:excluded()});$('#memoryStatus').textContent=r.text;}catch(e){$('#memoryStatus').textContent=e.message;}};
async function refreshStatus(){try{const data=await(await fetch('/api/status')).json();$('#connection').textContent='● Connected · on this PC';$('#coreState').textContent=data.core_ready?'Checkpoint available':'Training / preparing';const r=data.reports;let n=r.core?.examples_seen??r.core?.training_receipt?.examples_seen??r.core_recent?.at(-1)?.examples_seen;$('#exposures').textContent=n==null?'—':Number(n).toLocaleString();const counts=r.language_data?.counts;$('#corpus').textContent=counts?Object.values(counts).reduce((a,b)=>a+b,0).toLocaleString()+' rows':'Preparing';$('#evidence').textContent=JSON.stringify(r,null,2);}catch{$('#connection').textContent='Offline · start the local server';}}
drawIdle();refreshStatus();setInterval(refreshStatus,15000);
